### ISSUE TITLE
Update "Questions or comments" on all pages

### ISSUE THREAD

**Issue by emcwhirter-usgs** [usgs/geomag-website#125]
From @cafinn-usgs:

> We will need to update the “Questions or comments” links at the bottom of each of the Geomag web pages, and each pages’ email address should be tailored to the type of question that might arise. So the link on the “Monitoring” page should go to geomag-operations@geohazards.usgs.gov. The link on the data page should go to ...data..., etc. Currently, they all go to “geomagdata@usgs.gov”, and I’m not sure if anyone is even monitoring that email.

Based on this:
- **Monitoring** section should use geomag-operations
- **Data & Products** section should use geomag-data
- **Research** section should use geomag-research
- **Learn** section should probably use geomag-research?
- **Publications** section should use geomag-research
- **Services** section should use geomag-operations
- **Partners & Customers** section should use geomag-data?

**Comment by jmfee-usgs** [comment]
I'm not sure whether the questions and comments emails should go to the mailing lists first.  We're trying to send most web emails to ask@usgs.gov first, let them answer the majority of questions, and they forward on to the program as needed.

**Comment by cafinn-usgs** [comment]
Hmmm.  Good point.

**Comment by cafinn-usgs** [comment]
In my experience, questions sent to "ask" about geomagnetism are forwarded
to me!

On Thu, Nov 12, 2015 at 12:06 PM, Finn, Carol <cafinn@usgs.gov> wrote:

> Hmmm.  Good point.
>
>
> On Thu, Nov 12, 2015 at 10:24 AM, Jeremy Fee <notifications@github.com>
> wrote:
>
>> I'm not sure whether the questions and comments emails should go to the
>> mailing lists first. We're trying to send most web emails to ask@usgs.gov
>> first, let them answer the majority of questions, and they forward on to
>> the program as needed.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/usgs/geomag-website/issues/125#issuecomment-156173931>
>> .
>>
>
>


-- 
Jeffrey J. Love

USGS Advisor for Geomagnetic Research

303-273-8540

jlove@usgs.gov

https://profile.usgs.gov/jlove

**Comment by lisa-usgs** [comment]
Carol-

If no one is monitoring “geomagdata@usgs.gov”, we should request for it to be removed from the USGS email addresses.

I agree with Jeremy that all email should first go to the new SIS system, and they will then forward questions they can't answer (it may be all of them) to an email address you choose in order for a subject matter expert to respond.  However, you will need to choose one address for SIS to use, because they won't be able to (or want to) choose between 3 different geomag email addresses.

The new SIS Contact Us webpage is at https://answers.usgs.gov/.  SIS has asked us to use this for all email questions we're receiving, so I'll probably be using this approach very soon for the Earthquake and Landslides website too.

**Comment by lisa-usgs** [comment]
I updated the default contact link to go to the SIS form, but the geomag email addresses mentioned in this ticket can still be used on any page by adding $CONTACT = 'email-address@usgs.gov' at the top of the PHP file.
