### ISSUE TITLE
Beta Products lack descriptions

### ISSUE THREAD

**Issue by cafinn** [usgs/geomag-website#39]
We need to add some descriptive text for each of the Beta Products listed on this page:

http://dev-geomag.cr.usgs.gov/products/beta.php

It is not adequate to just list a name of a product and not include some description of what the product is or how it was derived.

**Comment by jmfee-usgs** [comment]
Carol, will you provide the descriptions or nominate someone in your group?

**Comment by cafinn** [comment]
Yes, I will nominate the eloquent Josh Rigler to provide you with the
descriptions of each of those beta products!

**Comment by erigler** [comment]
I propose we get rid of this page altogether. I believe we have a request in the queue to put together a Beta-like plots page similar to http://geomag.usgs.gov/plots (if not, we should), and we can document the Beta products properly as they come online. There are several reasons for doing this:

- many/most of these Beta products have been permanently or temporarily turned off anyway;
- the XY component page, at least, doesn't make sense, and besides, we are producing XYZ in a non-Beta mode anyway;
- the Dist+SQ stuff is being updated, but I don't think anyone is using this, and our plan is to scrap it this year for something better and simpler anyway...if it turns out someone *is* using it, and they complain, we can bring it back online and document it then;
- while Dst should probably be considered a Beta product, we've had it running in non-Beta mode for a long time now, and probably can't really turn back until we have a replacement ready to go.

Note that I am *not* proposing we discontinue any processing, or posting the data files online, so the Dist+SQ, AE, etc. that are still being generated and placed on Magweb for download should continue. I am only proposing we scrap the Beta **plots** page, which is all but useless right now anyway.

**Comment by emartinez-usgs** [comment]
There are also links to these beta products on the space weather page (/research/spaceweather.php). I think they should be removed if that is the direction we are going.

**Comment by erigler** [comment]
I never liked the spaceweather.php page. It is nothing but links to various (mostly Beta) data products, many of which are not currently being updated. As a "research" page, there should at least be links/citations to papers and other documentation related these products.

As I proposed [here](https://github.com/usgs/geomag-website/issues/36#issuecomment-139275758), can we remove the link to spaceweather.php from the research page, but keep the actual content, possibly linking to it from an internal "staging and evaluation" page so we can revisit and update it as time and resources allow?
